telegrambots:
  enable: true
  bots:
    username: CHECKING38_BOT
    token: ${TELEGRAM_BOT_TOKEN}
    admin:
      chat:
        id: ${TELEGRAM_ADMIN_CHAT_ID}
    webhook:
      enabled: false
spring:
  server:
    port: 8080
  data:
    redis:
      port: 6379
      timeout: 5000
      host: redis